FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
COPY mcp_server.py .
COPY pyproject.toml .
RUN pip install -r requirements.txt
RUN pip install mcpo uv

CMD ["uvx", "mcpo", "--host", "0.0.0.0", "--port", "8000", "--", "uv", "run", "mcp_server.py"]