FROM python:3.11-slim
WORKDIR /app
RUN pip install mcpo uv
COPY requirements.txt .
COPY mcp_server.py .
RUN pip install -r requirements.txt

CMD ["uvx", "mcpo", "--host", "0.0.0.0", "--port", "8000", "--", "uv", "run", "mcp_server.py"]